### ISSUE TITLE
Unable to generate output/data.pkl and output/humans.pkl after running the simulator

### ISSUE THREAD

**Issue by iamsharduld** [pg2455/covid_p2p_simulation#57]
Hello,

I recently tried to run the project on my local machine. After successfully running 

`python run.py sim --n_people 100 --n_stores 100 --n_parks 10 --n_misc 100 --init_percent_sick 0.01 --outfile data --seed 0
`
Two output files given in documentation are not generated by default. I was able to tweak code and generate `output/data.pkl` but couldn't do the same for `output/humans.pkl`

**Comment by mweiss17** [comment]
Hi @iamsharduld, I wrote out output/humans.pkl earlier to be used with the risk prediction code I was writing, but now we're doing everything with the logs in data.pkl. So, this is now the expected behaviour. I will update the documentation to reflect this. Sorry for the confusion, and thanks for raising the issue!

**Comment by mweiss17** [comment]
oh, also, the latest code for the risk prediction is here: https://github.com/mweiss17/covid_p2p_simulation/tree/models

It will be merged into master soon (within the next 24 hours), and we should provide a dataset for supervised learning risk prediction shortly thereafter as well as a website.
