### ISSUE TITLE
Calculation of R0

### ISSUE THREAD

**Issue by simonguist** [pg2455/covid_p2p_simulation#69]
# Prerequisites

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

# Expected Behavior
The basic reproduction number, R0, is defined as the expected number of secondary cases
produced by a single (typical) infection in a completely susceptible population
(https://web.stanford.edu/~jhj1/teachingdocs/Jones-on-R0.pdf)

 Disclaimer: I havn't read much about R0, so my understanding might also be wrong. 

# Current Behavior
https://github.com/pg2455/covid_p2p_simulation/blob/72e5d0e73a30ea4dc08d304350f91241898e88b8/track.py#L99-L104

As I unterstand, `n_infectious_contacts `is the number of people an individual has infected. For R0 in this function, only people that have infected others are considered: 

`if h.n_infectious_contacts > 0  
`
# Failure Information

Some people who got infected might not infect anybody else. Shoudn't we also take them into the average? (Otherwise R0 will always be equal or larger than 1 if the set is not empty)

Also, some people might have just gotten recently infected and will infect more others before not being infectious anymore.

## Possible Alternative

Maybe we can track all people who got infected and are not infectious anymore, or all people who have recovered. E.g., something like:

`h.n_infectious_contacts for h in self.city.humans if h.recovered_timestamp  > time_since_start 
`

## R vs R0

Additional point: R0 assumes a completely susceptible population. Probably the number calculated in this function should be R ( effective reproduction number)? [see Wikipedia](https://en.wikipedia.org/wiki/Basic_reproduction_number)

**Comment by pg2455** [comment]
I agree. Currently, we are not counting anyone in R0 who produced 0 infections. I guess this might be the solution -
`h.n_infectious_contacts for h in self.city.humans if h.state.index(1) > 0 `

It will include all those who were infected even if they have recovered.

**EDIT -** 
Above will produce an underestimate of R0. R0 is supposed to be expected cases produced by an infected person when the entire population is susceptible. I think we can keep track of `n_infectious_contacts` of those humans who were infected in the first week to estimate `R0`.

With regards to R vsR0 - As per my understanding, R needs to be computed with respect to time because infectious cases will change with time. R will be important to understand the efficacy of different interventions. Thanks for pointing that out.

**Comment by simonguist** [comment]
If I understand it correctly, this solution counts all people who got infected at some point.
Can we somehow only include people who finished the infectious state of the disease?
Otherwise we might underestimate R if this function is run during the pandemic: Some people who got infected recently and are still infectious might infect more people than they currently have (so their personal R will then be higher and is currently underestimated).

**Comment by pg2455** [comment]
If I understand it correctly, you are talking about R (effective reproductive number). I think it is computed as a function of time. At any time, it is defined as the `number of people infected by infectious people/the total number of infectious people`.

so that will look like this - 
`h.n_infectious_contacts for h in self.city.humans if h.state.index(1) == 2`

Is that what you meant?

**Comment by simonguist** [comment]
Yes, I mean R (effective reproductive number).  I'm also not sure what's the best way to calculate it.

What I mean is that if we take something like
 `number of people infected by infectious people/the total number of infectious people`
during the pandemic (while people are still being infectious) we underestimate R.

Simple example:
Assume: Every infectious person infects exactely one other person at a random timepoint while being infectious.
Then, at any timepoint, the average infectious person will have already infected `~ 0.5` people  (and will infect another `~ 0.5` later on) . The above formula would yield  `R ~ 0.5`, while in fact it should be `1`.

**Comment by pg2455** [comment]
After having a discussion with an epidemiologist, it seems reasonable to track R as an average infection per recovered person in the last 10 days. I implemented something similar [here](https://github.com/pg2455/covid_p2p_simulation/blob/improve_R/track.py#L176)

Let me know if you think this is what you pointed out earlier. It is keeping track of n_infectious_contacts and recovered people in last 10 days.

**Comment by simonguist** [comment]
Yes, this is what I was trying to point out. Wait until people finish their infectious period / have recovered, to see how many they have infected.

This new approach sounds good to me.

**Comment by pg2455** [comment]
Awesome! Thanks a lot for pointing it out. It was important 👍
